# Page settings
baseurl = "localhost:1313"
title = "Clofus Interconnect"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Ashwin"
  description = "Clofus Developer"
  email = "support@clofus.com"
  # Navigation
  [params.navigation]
    brand = "Clofus"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Reinventing Software User Experience through Simplicity."
    subtitle = 'Clofus helps your business to improve productivity, sales and streamline all your day-to-day activities'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    url = "#"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=rdFzgnKTIHs"


  # Work section
  [params.work]
    enable = true
    title = "Work"
    description = "See some of our proud customers with exemplary results."

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Clofus"
      subtitle = "Reinventing Education with Technology"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Beauty Advisor"
      subtitle = "A new way to discover inspiring looks, connect with experts, get advice & shop"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Ridezs"
      subtitle = "Drivers app for Carpool, Rideshare, Food delivery and Furniture Moving"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Abbot"
      subtitle = "Portfolio Website for an interior designer company"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Ecomate"
      subtitle = "Ecofriendly B2B Market Place for European Union Countries"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Fundingport"
      subtitle = "Peer to peer funding portal using bitcoins"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;With Clofus, management of teachers and allotting classes to them without any conflicts with their schedules has become precise and effortless.&rdquo;"
      person = 'Rajendran, Principal'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;With Clofus I can communicate to my students efficiently and give notify them about any new development all with the touch on this app.&rdquo;"
      person = 'Gayathri, Teacher'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Clofus provides us with the essential data of our son, like attendance, marks, etc. on our smartphone itself. This helps us to monitor the kids better.&rdquo;"
      person = 'Ramya, Parent'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "We build IoT, APIs, APPs, Websites & Deploy them to Scalable Cloud and its done using latest latest technologies."

    [[params.services.item]]
      title = "Clofus Products"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-social-dropbox"

    [[params.services.item]]
      title = "Website Developement"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-globe"

    [[params.services.item]]
      title = "Web Hosting"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-cloud-upload"

      [[params.services.item]]
      title = "Application Developement"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "&ldquo;Our focus is Innovation and we make products and not just projects.&rdquo;"

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]
      [[params.about.mission]]
        heading = "Introduction"
        description = "We are a software innovation products & services company focused on providing development & architecture support for innovative challenging projects that uses latest technology & frameworks, we have mix of both experience and young energetic trained developers in our company<br>We are highly focused on delivering scalable cloud application architecture, building product, prototyping the core concept, unit testing & programming scalable device independent web applications using latest technology, frameworks & follow agile methodology with exceptional quality of service and delivery"
        icon = 'icon-user'   
      
      [[params.about.mission]]
        heading = "Vision"
        description = "Our vision is towards providing value to the society by building products that reaches across various domains and to facilitate an Ideal work environment for our employees and provide exceptional quality to our customers<br>We have an efficient, young and enthusiastic team working closely together specializing a particular technology, We constantly learn and adapt to new technologies and frameworks to keep up with the latest trends "
        icon = 'icon-eye'   
      
      [[params.about.mission]]
        heading = "Specialities"
        description = "Software Development & Architecture Consultancy, Scalable & Distributed SOA Architecture, Innovations using latest software technologies, Responsive Front end design, Specialised in MEAN Stack, BigData & SAAS Applications, App Development and Agile Methodology"
        icon = 'icon-present'   
     
      [[params.about.mission]]
        heading = "Quality of service "
        description = "Clofus follows strict process in the entire development and delivery workflow, Using Modern tools such as project management tools, Continuous Integeration, Support Desk ticketing system and make sure the work progress is conveyed in a transparent manner to gain the confidence of our customers"
        icon = 'icon-badge'   

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1203
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 78
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    title = "Get in touch"
    description = "We'd love to help your innovation"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "177 First Floor Avs Complaex, <br> Velachery main road, Kamarajaburam <br> Chennai-600 073, Tamilnadu <br> India"],
        ["icon-phone", "(044)-2227 2044"],
        ["icon-envelope", "support@clofus.com"],
        ["icon-globe", '<a href="https://clofus.com/" target="_blank">clofus.com</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Submit"

  #  footer section
  [params.footer]
    enable = true
    copyright = '&copy; 2017 Clofus Innovations Private Limited (LLC). All Rights Reserved.'
